#!/bin/bash

#Global varibles
server='hjort@162.248.8.165'
rootpath='~/my-site'
page="$2.html"

function publish {
	#Put the name of the new file in the index over all posts.
	ssh $server "touch $rootpath/blog-posts/.post-index.txt && sed -i '1i $page' $rootpath/blog-posts/.post-index.txt"
}

#Creates a blog post and puts it up, but does not publish.
function put {

	#Generate markdown and push to server
	pandoc "$1" | ssh $server "cat > $rootpath/blog-posts/'$page'"
}

function delete {
    #Delete last post from index, but keep file
    ssh $server "ex -c ':1d' -c ':wq' $rootpath/blog-posts/.post-index.txt"
}

if [ $1 = "publish" ]; then 
	publish 
fi

if [ $1 = "put" ]; then
    put $2
fi

if [ $1 = "delete" ]; then
    delete
fi
